### ISSUE TITLE
[Bug] Request failed, status 502  

### ISSUE THREAD

**Issue by uPagge** [mcndt/noteshare.space#48]
**Describe the bug**
When I try to publish a note on my server, I get Request failed, status 502

**To Reproduce**
- Raise your noteshare service
- Make sure that the UI is displayed
- Try to publish any note

**Expected behavior**
I expected the note to be published. As a result, I get a Request failed, status 502

**Screenshots**
- Provide a screenshot showing what is wrong.
- If possible, share a note to noteshare.space and put the share link in this bug report so I can further debug the problem.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser safari
 - Version commit 655973a

**Additional context**
Here's what the backend container log shows

```log
{"level":50,"time":1685293069276,"pid":1,"hostname":"noteshare-backend","msg":"Error: Unable to load Node-API Library from /app/node_modules/.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt"}
/app/node_modules/@prisma/client/runtime/index.js:28837
      throw new PrismaClientInitializationError(message, this.client._clientVersion);
            ^

PrismaClientInitializationError: Unable to load Node-API Library from /app/node_modules/.prisma/client/libquery_engine-linux-musl.so.node, Library may be corrupt
    at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:28837:13)
    at PrismaClient._getDmmf (/app/node_modules/@prisma/client/runtime/index.js:29845:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PrismaClient._executeRequest (/app/node_modules/@prisma/client/runtime/index.js:29767:22)
    at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:29738:16) {
  clientVersion: '4.2.0',
  errorCode: undefined
}
```

When building the backend, I changed the Dockerfile because it wasn't going without it. Added at the very beginning
```
RUN apk update
RUN apk add --no-cache libssl1.1
```

It seems that something is missing when building a backend.

**Comment by uPagge** [comment]
It would be much easier if the collected images were available in DockerHub...

**Comment by uPagge** [comment]
Solved the problem by switching to node instead of node-alpine during server build
